# Learn Five Interesting Functions in PyTorch

We will check 5 interesting functions from PyTorch Documentation with several use cases each.

PyTorch is an open source machine learning library based on the Torch library, used for applications such as computer vision and natural language processing, primarily developed by Facebook's AI Research lab.( and about the chosen functions. )

- torch.zeros_like()
- torch.rand()
- torch.where()
- torch.randperm()
- torch.save()

Before we begin, let's install and import PyTorch

In [1]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
!pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 159.3 MB 4.1 kB/s  eta 0:00:01     |███████████████████████████████▏| 155.2 MB 23.1 MB/s eta 0:00:01
     |████████████████████████████████| 11.8 MB 19.5 MB/s eta 0:00:01
     |████████████████████████████████| 7.6 MB 1.3 MB/s eta 0:00:01


In [2]:
# Import torch and other required modules
import torch

## Function 1 - torch.zeros_like 

Returns a tensor filled with the scalar value 0, with the same size as input

In [3]:
# Example 1 - This examples create a Tensor t1 manually and then uses zeros_like to replicate it into a zeros tensor of same shape as the t1
t1 = torch.Tensor([[1, 2], [3, 4.]])
print(t1)
torch.zeros_like(t1)

tensor([[1., 2.],
        [3., 4.]])


tensor([[0., 0.],
        [0., 0.]])

zeros_like() creates a Tensor t1 manually and then uses zeros_like to replicate it into a zeros tensor of same shape as the t1

Below example creates a Tensor t2 having shape (2,5) and all values 3.141592 and then uses zeros_like to replicate it into a zeros tensor of same shape as t2

In [4]:
# Example 2 - working
t2 = torch.full((2, 5), 3.141592)
print(t2)
torch.zeros_like(t2)

tensor([[3.1416, 3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416, 3.1416]])


tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

zeros_like can create new tensors with any shape input tensor passed to it provided it the input tensor should be having correct dimensions


In [5]:
# Example 3 - gives an error here as it is required to pass an input parameter to this function

torch.zeros_like()

TypeError: zeros_like() missing 1 required positional arguments: "input"

zeros_like needs an input tensor to create a new tensor of zeros out of it

Hence zeros_like() comes handy when we need to create a tensor filled with zeros for the same dimensions as any given tensors which we already have into our codebase.

Let's save our work using Jovian before continuing.

In [6]:
!pip install jovian --upgrade --quiet

In [7]:
import jovian

<IPython.core.display.Javascript object>

In [13]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "lamoz9ra/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/lamoz9ra/01-tensor-operations


'https://jovian.ai/lamoz9ra/01-tensor-operations'

## Function 2 - torch.rand()

The torch.rand function is similar to the torch.arange function. However, it has some key differences that I felt made it a good subject for my second function. I will explain how the two functions are used differently in the examples below.


In [9]:
x= torch.tensor([[2,5,1],
               [4,2,5],
               [9,3,6]], dtype = torch.float32)
s= x.shape
y= torch.rand(s)
print(x)
print(y)

tensor([[2., 5., 1.],
        [4., 2., 5.],
        [9., 3., 6.]])
tensor([[0.5239, 0.8744, 0.5476],
        [0.8569, 0.2785, 0.9044],
        [0.0604, 0.6575, 0.4094]])


In this example I show that using the .rand function can quickly and easily generate a tensor with the same shape as x, that is populated with random intergers. It is important to note however, that while the .arange function uses intergers in a given range, the .rand function picks intergers that have a uniform distribution on the interval [0,1).  

In [10]:
x=torch.rand(5, dtype=torch.float32)
y= torch.arange(2,6.5,.5, dtype= torch.float32)
x1=torch.rand(10, dtype= torch.float32)
y1= torch.arange(0,1,.1, dtype=torch.float32)
print(x)
print(y,'\n')
print(x1)
print(y1)

tensor([0.7070, 0.2805, 0.2398, 0.4658, 0.8012])
tensor([2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000, 5.5000, 6.0000]) 

tensor([0.9736, 0.6853, 0.1251, 0.7347, 0.2692, 0.1264, 0.6086, 0.7506, 0.3234,
        0.6625])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])


Here I've shown that while both functions can be used to create tensors for any size, the .rand picks random values on a distribution curve from [0,1), and the .arange picks intergers that are evenly seperated between the start and end values. Thus, which one is necessary depends on the range of data you wish to generate.

In [11]:
torch.rand(1, dtype= int)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

Here I show that the dtype for .rand cannot be an int. This is because the distribution it selects numbers from is between, but non-inclusive of 0 & 1. Therefore the function can yield no whole number intergers.

In Summary, the .rand function is useful for creating a tensor that fits the shape of another tensor and contains values on an even distribution. This is useful for selecting weights as a starting point when beginning to train a predictive program. 

In [12]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "lamoz9ra/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/lamoz9ra/01-tensor-operations


'https://jovian.ai/lamoz9ra/01-tensor-operations'

## Function 3 - torch.where()

Return a tensor of elements selected from either x or y, depending on condition.

if x then x otherwise y.

In [97]:
# Example 1 - working
tx = torch.randn(3,2)
ty = torch.zeros_like(tx)
print(tx)
print(ty)
torch.where(tx == ty, tx, ty) #torch.where(condition, tensor1, tensor2) returns tensor1 or tensor2 depending on the condition

tensor([[ 0.0026, -0.4618],
        [ 0.1817,  1.1955],
        [ 0.7865,  0.5885]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

It returns ty as tx is not equal to ty. 

In [99]:
# Example 2 - working
torch.where(tx > 0, tx, ty)

tensor([[0.0026, 0.0000],
        [0.1817, 1.1955],
        [0.7865, 0.5885]])

Here it returns tx as tx > 0 is True

In [100]:
# Example 3 - breaking (to illustrate when it breaks)
torch.where(True, tx, ty)

TypeError: ignored

This fails because the condition passed in where() should be Tensor condition otherwise it fails with this error

Closing comments about when to use this function

In [101]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aneeshdalvi/01-tensor-operations


'https://jovian.ai/aneeshdalvi/01-tensor-operations'

## Function 4 - torch.randperm()

Returns a random permutation of integers from 0 to n - 1.

In [102]:
# Example 1 - working
torch.randperm(4)

tensor([3, 2, 0, 1])

It returns a tensor with random permutation of the upper bound which we provide to the function

In [103]:
# Example 2 - working
torch.randperm(10, dtype=torch.float64)

tensor([4., 1., 8., 2., 5., 3., 0., 6., 7., 9.], dtype=torch.float64)

You can create a tensor by specifying the dtype for the permutations as well

In [104]:
# Example 3 - breaking (to illustrate when it breaks)
torch.randperm(-2)

RuntimeError: ignored

You cannot pass negative dimension to the randperm() as a parameter. It must be an integer

torch.randperm() function can be usefull when you want the same tensor but change the permutation of it

In [ ]:
jovian.commit(project='01-tensor-operations')

## Function 5 - torch.save()

Saves a Tensor to a disk file.

In [105]:
# Example 1 - working
x = torch.tensor([0, 1, 2, 3, 4])
torch.save(x, 'tensor.pt')  

This command saves tensor as tensor.pt file in the files section of the notebook

In [14]:
# Example 2 - working
import io
buffer = io.BytesIO()
torch.save(x, buffer)  

You can also save the tensor as a buffer object

In [107]:
# Example 3 - breaking (to illustrate when it breaks)
torch.save()

TypeError: ignored

save() requires a tensor object to be passed in order to save it to a disk

This function is very usefull if you want to save some tensor and reuse it into a new notebook or reuse it somewhere else

In [108]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aneeshdalvi/01-tensor-operations


'https://jovian.ai/aneeshdalvi/01-tensor-operations'

## Conclusion

Today we covered interesting five functions from the Pytorch Documentation which would be useful in many ways while writing Machine Learning Applications. All the Five Functions where randomly picked and all have different useful use cases.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [15]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "lamoz9ra/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/lamoz9ra/01-tensor-operations


'https://jovian.ai/lamoz9ra/01-tensor-operations'