In [1]:
import numpy as np

In [2]:
a1 = [[111111.111, 2.222, 3.333, 4.444],
        [5.555, 6.666, 7.777, 8.888]]

np.round_(a1, decimals=-4)

array([[110000.,      0.,      0.,      0.],
       [     0.,      0.,      0.,      0.]])

In [11]:
arr2 = np.array([[5, 1, 6],
                 [9,12,15],
                 [21,97,1]])
np.sort(arr2, kind="mergesort")[:,::-1]

array([[ 6,  5,  1],
       [15, 12,  9],
       [97, 21,  1]])

In [21]:
np.sort(arr2, kind="mergesort")[:,::-1]

array([[ 6,  5,  1],
       [15, 12,  9],
       [97, 21,  1]])

In [22]:
arr1=[[1,1,3],
      [4,2,3]]
np.histogram(arr1)

(array([2, 0, 0, 1, 0, 0, 2, 0, 0, 1]),
 array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7, 4. ]))